export enum PublicationTypes {
  mainNews = 'Главная новость',
  urgentNews = 'Срочная новость',
  investigation = 'Расследование',
  reportage = 'Репортаж',
  interview = 'Интервью',
  politicalArticle = 'Политическая статья',
  economicReview = 'Экономический обзор',
  culturalReview = 'Культурное обозрение',
  sportsReport = 'Спортивный отчёт',
  scientificPopularArticle = 'Научно-популярная статья',
  humorousNote = 'Юмористическая заметка',
  anecdote = 'Анекдот',
  crosswordPuzzle = 'Кроссворд/Головоломка',
  horoscope = 'Гороскоп',
  recipe = 'Рецепты',
  weather = 'Погода',
  currencyCourses = 'Курсы валют',
  televisionProgram = 'Телепрограмма',
  eventProgram = 'Афиша мероприятий',
  announcement = 'Объявления',
  editorColumn = 'Редакторская колонка',
  readerLetters = 'Письма читателей',
  analytics = 'Аналитика',
  photoReport = 'Фоторепортаж',
}

export enum ServiceTypes {
  advertisement = 'Публикация рекламного объявления',
  articleAdvertisement = 'Публикация рекламной статьи',
  vacancy = 'Размещение вакансий',
  greeting = 'Размещение поздравлений',
  obituary = 'Размещение некрологов',
  archive = 'Архивная выписка',
  personal = 'Печать персонализированного выпуска',
  theme = 'Заказ тематического набора статей',
}
